---
title: |
  Glass Defect Detection:
  Evaluating Object Detection Models
institute: "Institue of Computational Life Science"
keywords: "Deep Learning, Object Detectors, Image Processing, Evaluation Metrics"
lang: en
confidential: true
cover-image:
  src: Cover-image.jpg
  max-width: 100%
  max-height: 7cm
thesis-type: "Projectwork 2"
degree-type: "Bachelors"
study-year: "2023"
submission-date: "2025-12-11"
study-direction: "Applied Digital Life Science"
supervisors:
  - title: "Dr."
    name: "Stefan Glüge"
    affiliation: "ZHAW Life Sciences und Facility Management, Wädenswil"

bibliography: references.bib
author: 
  - Florian Vollmer
format: 
  zhaw-lsfm-typst: default
  html: default
---

# Abstract {.unnumbered .unlisted}

Write after work is written


::: {.content-hidden when-format="html"}

# Table of Contents {.unnumbered .unlisted}

{{< table-of-contents >}}

:::



# List of abbrevations {.unnumbered}

Potential abbrevations

# Introduction
## Context and Motivation
In the current technological landscape, the implementation of modern technologies is indispensable for ensuring precise and automated processes. Within the industrial sector, quality control represents a critical success factor. Specifically in pharmaceuticals and medical technology, the integrity of the primary packaging material (typically glass containers) is crucial for product safety.

The primary material used for medical and chemical glass containers generally consists of borosilicate glass. However, this material can exhibit or contain production-related defects, including particulate inclusions, air bubbles, or flexible fragments known as Lamellae [@Foglia2015AnIS].

The relevance of these quality deficiencies is highlighted by the consequences demonstrated by [@Foglia2015AnIS]: _"In recent years, more than 20
product recalls have been associated with glass issues, and over 100 million units of drugs packaged in vials or syringes have been withdrawn from the
market."_ This underscores the urgent necessity of reliable detection methods for such flaws.

The rapid advancement of Artificial Intelligence (AI) and fundamental mechanisms like Deep Learning allows for the application of so-called object detectors for the automated recognition of the aforementioned defects. The attractiveness of these AI-based image recognition methods is continuously increasing [@10.1115/1.4049535]. However, as these procedures still represent a nascent field of research, comprehensive validation studies on their suitability and the achievability of the necessary performance in industrial use are lacking.

A central challenge in training robust models is the scarcity of extensive datasets [@10.1115/1.4049535]. Specifically, the naturally limited availability of data from defective products, caused by the significant imbalance in favor of intact units, complicates the creation of an adequate training dataset [@10.1115/1.4049535].

This paper serves as an exploratory contribution to the evaluation of the current feasibility of AI-supported defect detection. The objective of this work is the comparison of available models on the market and the existence of suitable datasets, in order to provide a well-founded statement on the realisability of precise defect determination.

## Overall Concept
The overall objective of this work was to conduct a quantitative performance comparison of two different object detection models under varying data conditions. The experimental procedure was based on the following fundamental steps:

1. **Model selection and preparation:** Two specific, pre-trained foundation models from the class of object detectors were selected and initialized for evaluation.

2. **Data management and fine-tuning:** To test the models' generalizability, they were each adapted to the specific classification task (defect detection) using two discrete datasets (dataset A and dataset B) via a fine-tuning process.

3. **Performance evaluation:** The performance of the four trained model-dataset combinations was then evaluated on a separate, previously unseen test dataset. The performance was determined based on established quantitative metrics for object detection.

4. **Comparative analysis:** Finally, the generated results were visualized and subjected to a detailed comparative analysis. The aim was to identify the robustness, strengths, and weaknesses of the model architectures examined in relation to glass defect detection.

## Research Questions
Based on the challenges mentioned in **[Context and Motivation](#context-and-motivation)**, this study tries to answer following research questions:

- How does the performance differ between the two investigated object detection models (Model X vs. Model Y), measured by Mean Average Precision (mAP), in detecting defects in the different datasets?
- Which performance benchmarks (e.g., minimum precision and recall values) must be achieved to deem the resulting reliability of the models as sufficient for deployment in real-world quality control scenarios?

## State of the Art

# Methodology
## Datasets and Assumptions
## Model Selection
Die Entscheidung der Modellwahl hat sich auf die momentan zwei bekanntesten Objekt deketoren konzentriert. Zum einen gibt es das sogenannte YOLO Modell (You Only Look Once). Dies stammt von dem Chinesischen Software Entwickler Ultralytics. Es ist ein Echtzeit-Objekterkennungs und Bildsegmentierungsmodell. 
## Model Finetuning
## Model Training
## Model Testing
## Evaluation Metrics

# Results
## Model Results and Statistical Evaluation
## Quantitative and Qualitative Evaluation
## Evaluation Visualization

# Discussion
## Interpretation of Results
## Comparison with Expectations

# Conclusion
## Summary of Key Findings
## Limitations and Challenges
## Future Research Directions


# References {#sec-refs}

{{< references >}}

::: {.content-hidden when-format="html"}

# Lists

## List of Figures {.unnumbered}

{{< list-of-figures >}}

## List of Tables {.unnumbered}

{{< list-of-tables >}}

:::

# Attachments
